#!/bin/sh

# Available governors system dependent, but the list is:
# Performance, Ondemand, Conservative, Powersave
# Usage: scale GOVERNOR

if [ $1 > /dev/null 2>&1 ]
   then
        for i in 0 1;
            do
                su -c "/usr/bin/cpufreq-set -c $i -g $1";
            done

        echo "governor set to $1"
   else
        echo "No governor parameter given!"
fi
exit 0;

